spring:
  application:
    name: gyeongdan
  jpa:
    properties:
      hibernate:
        format_sql: true
        ddl-auto: update
    show_sql: true

logging:
  level:
    org:
      springframework:
        web: DEBUG
